apiVersion: v1
kind: Pod
metadata:
  name: ceph-rbd-test-pod
spec:
  containers:
  - name: ceph-busybox
    image: busybox
    command: ["sleep", "60000"]
    volumeMounts:
    - name: ceph-rbd-vol
      mountPath: /usr/share/busybox
      readOnly: false
  volumes:
  - name: ceph-rbd-vol
    persistentVolumeClaim:
      claimName: ceph-rbd-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-rbd-claim
spec:
  accessModes:  
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

